config/routes.rb
Rails.application.routes.draw do
  get '/server_timestamp', to: 'server_timestamp#show'

  post '/client_event_proxy', to: 'client_event_proxy#create'

  resources :todos, only: %i[index show new create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Instrument all activerecord actions for tracing

  around_save do |activity, block|
    with_span("ActiveRecord#save #{activity.class.name}") do
      block.call
    end
  end

  around_destroy do |activity, block|
    with_span("ActiveRecord#destroy #{activity.class.name}") do
      block.call
    end
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  attribute :key

  def key
    self[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Don't worry about form authenticity tokens in this simple example app
  skip_before_action :verify_authenticity_token

  around_action :wrap_in_tracing_span

  private

  def wrap_in_tracing_span
    with_span("#{controller_name}##{action_name}") do
      yield
    end
  end
end

app/controllers/client_event_proxy_controller.rb
class ClientEventProxyController < ApplicationController
  # POST /client_event_proxy.json
  def create
    event = params.fetch(:event).to_h
    start_timestamp_string = event.fetch(:timestamp)
    event.delete('timestamp')
    start = Time.at(start_timestamp_string.to_i / 1000)
    # the Ruby libhoney API wants the timestamp specified separately as a Ruby Time object,
    # not as part of the event data
    send_event(event, start)

    # could return more info, but for this example just return empty response
    render json: {}.as_json
  end
end

app/controllers/server_timestamp_controller.rb
class ServerTimestampController < ApplicationController
  def show
    render json: { server_timestamp: DateTime.now.strftime('%Q') }.as_json
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    params.require(:todo).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoneycombRailsFullstackTracing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/index.html.erb
<h1>REACT:</h1>

<div id="todoapp"></div>
<%= javascript_pack_tag 'application' %>

<h1>RAILS:</h1>

<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.text %></td>
        <td><%= link_to 'Show', todo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<%= link_to 'Back', todos_path %>